name: venv2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - addict=2.4.0
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.0.5
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.4.0
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - ffmpeg=4.2.2
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.13.3
  - glib=2.84.2
  - glib-tools=2.84.2
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h5py=3.11.0
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.10
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.15.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libkrb5=1.21.3
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libvpx=1.7.0
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql=8.4.0
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.1
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.5.2
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.46.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.6.0
  - qtpy=2.4.1
  - readline=8.3
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.50.2
  - stack_data=0.2.0
  - sympy=1.13.3
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.15
  - tomli=2.0.1
  - torchaudio=2.1.2
  - torchtriton=2.1.0
  - torchvision=0.16.2
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.10
  - x264=1!157.20191217
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
prefix: /home/aijia/miniconda3/envs/venv2
